version: '3.7'

services:
  sat-app:
    container_name: sat-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always

  sat-mysql:
    image: mysql:8.0
    container_name: sat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sat_db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
